
spring:
  rabbitmq:
    host: 192.168.253.8
    port: 5672
  cloud:
    stream:
      bindings:
        myQueue:
          input: input
          group: group1
          content-type: application/json
          destination: exchange
server:
  port: 8080