spring:
  datasource:
    username: lj_test
    password: 1
    url: jdbc:mysql://192.168.253.8:3306/ljzf_device_data
max:
  generator:
    output-dir: /code-generator/src/main/java
    package-name: com.wqb.codegenerator
    author: benwq